name: Scrimmage
version: 2.0
main: me.rainoboy97.scrimmage.Scrimmage
author: RainoBoy97
authors: [ShinyDialga45, bookofnathan, msalihov, AtroAtomx]
commands:
  adminchat:
    description: Chat with other OPs
    aliases: [a, ac]
  start:
    description: Start the match.
    aliases: [begin]
  cancel:
    description: Cancel the current countdown.
    aliases: [cancelcountdown, stopcountdown]
  end:
    description: End the current match.
    aliases: [endmatch, finish]
  join:
    description: Join a team
    aliases: [j]
  setmatch:
    description: Load a match
    aliases: [setnext,loadmatch,cycle,sn,sm,lm,cyc]
  reloadmaps:
    description: Reloads maps
    aliases: [rlm, rlmaps, rmaps]
  g:
    description: Talk in global chat.
    aliases: [global, talk]
  operators:
    description: List all operators.
    aliases: [ops, staff]
  pvp:
    description: Toggle PVP
  maps:
    description: List loaded maps
    aliases: [loadedmaps]
  match:
    description: Information about match
    aliases: [matchinfo]
