name: Scrimmage
version: 2.0
main: me.rainoboy97.scrimmage.Scrimmage
author: RainoBoy97
authors: [XX_iiShockzz_XX, hdt80bro, ShinyDialga45, bookofnathan, msalihov]
commands:
  start:
    description: Start the match.
    aliases: [begin]
  cycle:
    description: Cycle between maps.
    aliases: [cyc]
  cancel:
    description: Cancel the current countdown.
    aliases: [cancelcountdown, stopcountdown]
  end:
    description: End the current match.
    aliases: [endmatch, finish]
  join:
    description: Join a team
    aliases: [j]
  g:
    description: Talk in global chat.
    aliases: [global, talk]
  setnext:
    description: Set the next map.
    aliases: [sn]
  a:
    description: Admin chat.
  operators:
    description: List all operators.
    aliases: [ops, staff]
  pvp:
    description: Toggle PVP
  match:
    description: Information about match
    aliases: [matchinfo]
