name: Scrimmage
version: 2.0
main: me.rainoboy97.scrimmage.Scrimmage
authors: [RainoBoy97, XX_iiShockzz_XX, hdt80bro, ShinyDialga45, bookofnathan]
depends: [TagAPI]
commands:
  start:
    description: Start the match.
    aliases: [begin]
  cycle:
    description: Cycle between maps.
  cancel:
    description: Cancel the current countdown.
  end:
    description: End the current match.
  join:
    description: Join a team
    aliases: [j]
  g:
    description: Talk in global chat.
  setnext:
    description: Set the next map.
    aliases: [sn]
  a:
    description: Admin chat.
  operators:
    description: List all operators.
    aliases: [ops]
  pvp:
    description: Toggle PVP
