name: Scrimmage
version: 1.0
main: me.rainoboy97.scrimmage.Scrimmage
authors: [RainoBoy97, XX_iiShockzz_XX]
depends: [TagAPI]
commands:
  start:
    description: Scrimmage command
    aliases: [begin]
  cycle:
    description: Scrimmage command
  cancel:
    description: Scrimmage command
  end:
    description: Scrimmage command
  join:
    description: Scrimmage command
  g:
    description: Scrimmage command
  setnext:
    description: Scrimmage command
    aliases: [sn]
  a:
    description: Scrimmage command
  operators:
    description: Scrimmage command
    aliases: [ops]
  pvp:
    description: Scrimmage command
